// Code generated by protoc-gen-go.
// source: self-describing-message.proto
// DO NOT EDIT!

package dicoprotos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SelfDescribingMessage_MessageType int32

const (
	SelfDescribingMessage_DO_TASK     SelfDescribingMessage_MessageType = 1
	SelfDescribingMessage_TASK_STATUS SelfDescribingMessage_MessageType = 2
	SelfDescribingMessage_TASK_RESULT SelfDescribingMessage_MessageType = 3
	SelfDescribingMessage_SUBMIT_TASK SelfDescribingMessage_MessageType = 4
	SelfDescribingMessage_HANDSHAKE   SelfDescribingMessage_MessageType = 5
)

var SelfDescribingMessage_MessageType_name = map[int32]string{
	1: "DO_TASK",
	2: "TASK_STATUS",
	3: "TASK_RESULT",
	4: "SUBMIT_TASK",
	5: "HANDSHAKE",
}
var SelfDescribingMessage_MessageType_value = map[string]int32{
	"DO_TASK":     1,
	"TASK_STATUS": 2,
	"TASK_RESULT": 3,
	"SUBMIT_TASK": 4,
	"HANDSHAKE":   5,
}

func (x SelfDescribingMessage_MessageType) Enum() *SelfDescribingMessage_MessageType {
	p := new(SelfDescribingMessage_MessageType)
	*p = x
	return p
}
func (x SelfDescribingMessage_MessageType) String() string {
	return proto.EnumName(SelfDescribingMessage_MessageType_name, int32(x))
}
func (x *SelfDescribingMessage_MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SelfDescribingMessage_MessageType_value, data, "SelfDescribingMessage_MessageType")
	if err != nil {
		return err
	}
	*x = SelfDescribingMessage_MessageType(value)
	return nil
}
func (SelfDescribingMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{0, 0}
}

type SelfDescribingMessage struct {
	Type             *SelfDescribingMessage_MessageType `protobuf:"varint,1,req,name=type,enum=dicoprotos.SelfDescribingMessage_MessageType" json:"type,omitempty"`
	Data             []byte                             `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *SelfDescribingMessage) Reset()                    { *m = SelfDescribingMessage{} }
func (m *SelfDescribingMessage) String() string            { return proto.CompactTextString(m) }
func (*SelfDescribingMessage) ProtoMessage()               {}
func (*SelfDescribingMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *SelfDescribingMessage) GetType() SelfDescribingMessage_MessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return SelfDescribingMessage_DO_TASK
}

func (m *SelfDescribingMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SelfDescribingMessage)(nil), "dicoprotos.SelfDescribingMessage")
	proto.RegisterEnum("dicoprotos.SelfDescribingMessage_MessageType", SelfDescribingMessage_MessageType_name, SelfDescribingMessage_MessageType_value)
}

var fileDescriptor2 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x4e, 0xcd, 0x49,
	0xd3, 0x4d, 0x49, 0x2d, 0x4e, 0x2e, 0xca, 0x4c, 0xca, 0xcc, 0x4b, 0xd7, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0xc9, 0x4c, 0xce, 0x07,
	0x33, 0x8b, 0x95, 0x0e, 0x30, 0x72, 0x89, 0x06, 0x03, 0x55, 0xbb, 0xc0, 0x15, 0xfb, 0x42, 0xd4,
	0x0a, 0x59, 0x73, 0xb1, 0x94, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x69, 0xf0, 0x19, 0xe9,
	0xea, 0x21, 0x34, 0xe9, 0x61, 0xd5, 0xa0, 0x07, 0xa5, 0x43, 0x80, 0x9a, 0x84, 0x78, 0xb8, 0x58,
	0x52, 0x12, 0x4b, 0x12, 0x25, 0x98, 0x80, 0x9a, 0x79, 0x94, 0x62, 0xb8, 0xb8, 0x91, 0x25, 0xb9,
	0xb9, 0xd8, 0x5d, 0xfc, 0xe3, 0x43, 0x1c, 0x83, 0xbd, 0x05, 0x18, 0x85, 0xf8, 0xb9, 0xb8, 0x41,
	0xac, 0xf8, 0xe0, 0x10, 0xc7, 0x90, 0xd0, 0x60, 0x01, 0x26, 0xb8, 0x40, 0x90, 0x6b, 0x70, 0xa8,
	0x4f, 0x88, 0x00, 0x33, 0x48, 0x20, 0x38, 0xd4, 0xc9, 0xd7, 0x33, 0x04, 0xa2, 0x85, 0x45, 0x88,
	0x97, 0x8b, 0xd3, 0xc3, 0xd1, 0xcf, 0x25, 0xd8, 0xc3, 0xd1, 0xdb, 0x55, 0x80, 0x15, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xb7, 0x3f, 0x10, 0x20, 0xee, 0x00, 0x00, 0x00,
}
