// Code generated by protoc-gen-go.
// source: task-status.proto
// DO NOT EDIT!

package dicoprotos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TaskStatus_TaskStatusUpdate int32

const (
	TaskStatus_REGISTERED TaskStatus_TaskStatusUpdate = 0
	TaskStatus_STARTED    TaskStatus_TaskStatusUpdate = 1
	TaskStatus_FINISHED   TaskStatus_TaskStatusUpdate = 2
	TaskStatus_FAILED     TaskStatus_TaskStatusUpdate = 3
)

var TaskStatus_TaskStatusUpdate_name = map[int32]string{
	0: "REGISTERED",
	1: "STARTED",
	2: "FINISHED",
	3: "FAILED",
}
var TaskStatus_TaskStatusUpdate_value = map[string]int32{
	"REGISTERED": 0,
	"STARTED":    1,
	"FINISHED":   2,
	"FAILED":     3,
}

func (x TaskStatus_TaskStatusUpdate) Enum() *TaskStatus_TaskStatusUpdate {
	p := new(TaskStatus_TaskStatusUpdate)
	*p = x
	return p
}
func (x TaskStatus_TaskStatusUpdate) String() string {
	return proto.EnumName(TaskStatus_TaskStatusUpdate_name, int32(x))
}
func (x *TaskStatus_TaskStatusUpdate) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TaskStatus_TaskStatusUpdate_value, data, "TaskStatus_TaskStatusUpdate")
	if err != nil {
		return err
	}
	*x = TaskStatus_TaskStatusUpdate(value)
	return nil
}
func (TaskStatus_TaskStatusUpdate) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor5, []int{0, 0}
}

type TaskStatus struct {
	Id               *int64                       `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Type             *TaskStatus_TaskStatusUpdate `protobuf:"varint,2,req,name=type,enum=dicoprotos.TaskStatus_TaskStatusUpdate" json:"type,omitempty"`
	Options          *string                      `protobuf:"bytes,3,req,name=options" json:"options,omitempty"`
	Runtime          *int64                       `protobuf:"varint,4,opt,name=runtime" json:"runtime,omitempty"`
	WorkerId         *int64                       `protobuf:"varint,5,opt,name=worker_id" json:"worker_id,omitempty"`
	TaskGroup        *int64                       `protobuf:"varint,6,opt,name=task_group" json:"task_group,omitempty"`
	Retries          *int64                       `protobuf:"varint,7,opt,name=retries,def=0" json:"retries,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *TaskStatus) Reset()                    { *m = TaskStatus{} }
func (m *TaskStatus) String() string            { return proto.CompactTextString(m) }
func (*TaskStatus) ProtoMessage()               {}
func (*TaskStatus) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

const Default_TaskStatus_Retries int64 = 0

func (m *TaskStatus) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *TaskStatus) GetType() TaskStatus_TaskStatusUpdate {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return TaskStatus_REGISTERED
}

func (m *TaskStatus) GetOptions() string {
	if m != nil && m.Options != nil {
		return *m.Options
	}
	return ""
}

func (m *TaskStatus) GetRuntime() int64 {
	if m != nil && m.Runtime != nil {
		return *m.Runtime
	}
	return 0
}

func (m *TaskStatus) GetWorkerId() int64 {
	if m != nil && m.WorkerId != nil {
		return *m.WorkerId
	}
	return 0
}

func (m *TaskStatus) GetTaskGroup() int64 {
	if m != nil && m.TaskGroup != nil {
		return *m.TaskGroup
	}
	return 0
}

func (m *TaskStatus) GetRetries() int64 {
	if m != nil && m.Retries != nil {
		return *m.Retries
	}
	return Default_TaskStatus_Retries
}

func init() {
	proto.RegisterType((*TaskStatus)(nil), "dicoprotos.TaskStatus")
	proto.RegisterEnum("dicoprotos.TaskStatus_TaskStatusUpdate", TaskStatus_TaskStatusUpdate_name, TaskStatus_TaskStatusUpdate_value)
}

var fileDescriptor5 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xdd, 0xa4, 0x36, 0x76, 0x94, 0xfe, 0xd9, 0xd3, 0xe2, 0xa9, 0xf4, 0xa2, 0x97, 0x06,
	0x11, 0xbc, 0x78, 0x6b, 0x31, 0xd5, 0x05, 0x11, 0x49, 0xe2, 0xb9, 0x84, 0x64, 0xd1, 0xa5, 0xa4,
	0xbb, 0xec, 0x4e, 0x90, 0x7c, 0x72, 0xaf, 0x4e, 0xa2, 0x10, 0xc1, 0xdb, 0x7b, 0x8f, 0x79, 0xfb,
	0x9b, 0x1d, 0x58, 0x60, 0xe1, 0x0f, 0x6b, 0x8f, 0x05, 0x36, 0x3e, 0xb6, 0xce, 0xa0, 0xe1, 0x50,
	0xe9, 0xd2, 0xf4, 0xd2, 0xaf, 0xbe, 0x18, 0x40, 0x4e, 0x13, 0x59, 0x3f, 0xc0, 0x01, 0x02, 0x5d,
	0x09, 0xb6, 0x0c, 0xae, 0x43, 0x7e, 0x07, 0x23, 0x6c, 0xad, 0x12, 0x01, 0xb9, 0xe9, 0xed, 0x55,
	0x3c, 0xb4, 0xe2, 0xa1, 0xf1, 0x47, 0xbe, 0xd9, 0xaa, 0x40, 0xc5, 0x67, 0x10, 0x19, 0x8b, 0xda,
	0x1c, 0xbd, 0x08, 0xa9, 0x39, 0xe9, 0x02, 0xd7, 0x1c, 0x51, 0xd7, 0x4a, 0x8c, 0x96, 0x8c, 0x1e,
	0x5e, 0xc0, 0xe4, 0xd3, 0xb8, 0x83, 0x72, 0x7b, 0x62, 0x9d, 0xf6, 0x11, 0x81, 0xbb, 0x3d, 0xf7,
	0xef, 0xce, 0x34, 0x56, 0x8c, 0x7f, 0xb3, 0xc8, 0x29, 0x74, 0x5a, 0x79, 0x11, 0x75, 0xc1, 0x3d,
	0xbb, 0x59, 0x49, 0x98, 0xff, 0x03, 0x4e, 0x01, 0xd2, 0xe4, 0x51, 0x66, 0x79, 0x92, 0x26, 0x0f,
	0xf3, 0x13, 0x7e, 0x0e, 0x51, 0x96, 0x6f, 0xd2, 0x9c, 0x0c, 0xe3, 0x17, 0x70, 0xb6, 0x93, 0x2f,
	0x32, 0x7b, 0x22, 0x17, 0x10, 0x65, 0xbc, 0xdb, 0xc8, 0x67, 0xd2, 0xe1, 0x76, 0x0d, 0x97, 0xa5,
	0xa9, 0xe3, 0xf2, 0x43, 0x39, 0xd7, 0xd2, 0x3e, 0x75, 0xff, 0xc1, 0x9f, 0x13, 0xf9, 0xed, 0x6c,
	0xc0, 0xbc, 0x76, 0xc9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x65, 0xd4, 0x03, 0x48, 0x01,
	0x00, 0x00,
}
